import { imgUrl } from "@/constants";
import { IProduct } from "@/interface/app.interface";
import { API_REQUEST } from "@/service/api.service";
import { GetServerSideProps } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home({ allPro }: HomeProps): JSX.Element {
  return (
    <>
      <Head>
        <title>Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <div className="bg-white">
        <div className="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
          <h2 className="sr-only">Products</h2>

          <div className="grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">
            {allPro.map((item) => (
              <Link key={item.category_name} href="#" className="group">
                <div className="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-lg bg-gray-200 xl:aspect-h-8 xl:aspect-w-7">
                  <Image
                    src={`${imgUrl}${item.image.replace(
                      "http://localhost:2001",
                      ""
                    )}`}
                    alt=""
                    width={100}
                    height={100}
                    className="h-full w-full object-cover object-center group-hover:opacity-75"
                  />
                </div>
                <h3 className="mt-4 text-sm text-gray-700">{item.title}</h3>
                <p className="mt-1 text-lg font-medium text-gray-900">
                  {item.price} so`m
                </p>
              </Link>
            ))}
          </div>
        </div>
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
  const allPro = await fetch(API_REQUEST.allProduct).then((res) => res.json());

  return {
    props: {
      allPro: allPro,
    },
  };
};

interface HomeProps {
  allPro: IProduct[];
}
